[package]
name = "task1"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15.11"
futures = "0.3.31"
serde = "1.0.219"
solana-client = "2.2.3"
solana-sdk = "2.2.1"
tokio = { version = "1.44.1", features = ["full"] }
