[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.5"
solana-client = "2.2.3"
solana-sdk = "2.2.1"
program = { path = "../program", version = "0.1.0", features = ["no-entrypoint"] }