from_wallets:
  - "task2/wallet1.json"
  - "task2/wallet2.json"
  - "task2/wallet1.json"
  - "task2/wallet2.json"
  - "task2/wallet1.json"
  - "task2/wallet2.json"
  - "task2/wallet1.json"
  - "task2/wallet2.json"
  - "task2/wallet1.json"
  - "task2/wallet2.json"
  - "task2/wallet1.json"
  - "task2/wallet2.json"
  - "task2/wallet1.json"
  - "task2/wallet2.json"
  - "task2/wallet1.json"
  - "task2/wallet2.json"
to_wallets:
  - "5LoqDNVGvD9f7MsNpaU4ajtqFypfBEjSvu6gBuN7aYpP"
  - "GkY7HuzNXf19uiUL6enqwYQ69d5am2rSNdP9m3rCfF1L"
  - "5LoqDNVGvD9f7MsNpaU4ajtqFypfBEjSvu6gBuN7aYpP"
  - "GkY7HuzNXf19uiUL6enqwYQ69d5am2rSNdP9m3rCfF1L"
  - "5LoqDNVGvD9f7MsNpaU4ajtqFypfBEjSvu6gBuN7aYpP"
  - "GkY7HuzNXf19uiUL6enqwYQ69d5am2rSNdP9m3rCfF1L"
  - "5LoqDNVGvD9f7MsNpaU4ajtqFypfBEjSvu6gBuN7aYpP"
  - "GkY7HuzNXf19uiUL6enqwYQ69d5am2rSNdP9m3rCfF1L"
  - "5LoqDNVGvD9f7MsNpaU4ajtqFypfBEjSvu6gBuN7aYpP"
  - "GkY7HuzNXf19uiUL6enqwYQ69d5am2rSNdP9m3rCfF1L"
  - "5LoqDNVGvD9f7MsNpaU4ajtqFypfBEjSvu6gBuN7aYpP"
  - "GkY7HuzNXf19uiUL6enqwYQ69d5am2rSNdP9m3rCfF1L"
  - "5LoqDNVGvD9f7MsNpaU4ajtqFypfBEjSvu6gBuN7aYpP"
  - "GkY7HuzNXf19uiUL6enqwYQ69d5am2rSNdP9m3rCfF1L"
  - "5LoqDNVGvD9f7MsNpaU4ajtqFypfBEjSvu6gBuN7aYpP"
  - "GkY7HuzNXf19uiUL6enqwYQ69d5am2rSNdP9m3rCfF1L"
amount: 1000000 # сумма перевода в лампортах (например, 1_000_000 = 0.001 SOL)
